version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    env_file: .env
    environment:
      - DUCOR_EOS_RETHINKHOST=rethinkdb
    depends_on:
      - rethinkdb
    restart: on-failure

  rethinkdb:
    image: "rethinkdb"
    ports:
      - "28015:28015"