version: '3'

services:
  devapi:
    build:
      context: ../ducor-frontend
      dockerfile: Dockerfile-devapi
      args:
        - DUCOR_FRONT_URL=client_test
        - DUCOR_FRONT_PORT=80
        - DUCOR_API_URL=devapi
        - DUCOR_API_PORT=3093
    ports:
      - "3093:3093"

  client_test:
    build:
      context: ../ducor-frontend
      dockerfile: Dockerfile
      args:
        - DUCOR_FRONT_URL=client_test
        - DUCOR_FRONT_PORT=80
        - DUCOR_API_URL=devapi
        - DUCOR_API_PORT=3093
    volumes:
      - ../ducor-frontend/build:/app/build
    ports:
      - "80:80"
    env_file: []
    depends_on:
      - devapi

  test:
    build:
      context: ../ducor-frontend
      dockerfile: Dockerfile-cypress
    volumes:
      - ../ducor-frontend/:/app
    working_dir: /app
    environment:
      - CYPRESS_URL=client_test
      - CYPRESS_PORT=80
    command: "npm run test"
    depends_on:
      - devapi
      - client_test